### ISSUE TITLE
what is the function of alpha with value 0.005?

### ISSUE THREAD

**Issue by Milraga19** [MuhammadAhmed8/Vector-Space-Model-IR#1]
i just dont understand about alpha with value 0.005 for filtered result. what is the function of alpha with value 0.005 for filtered result?

**Comment by MuhammadAhmed8** [comment]
Alpha is used as the threshold value to filter out docs whose scores are less than the alpha value. You can find it in the search.py file.

**Comment by Milraga19** [comment]
> Alpha is used as the threshold value to filter out docs whose scores are less than the alpha value. You can find it in the search.py file. 

Oh I see, thanks for the information!😁
